# Detailed explanation of all options available at https://github.com/NEZNAMY/TAB/wiki/config.yml

change-nametag-prefix-suffix: true
change-tablist-prefix-suffix: true
enable-header-footer: false
header:
- '&3&lServer name'
- '&6&lRank: %rank%'
- '&7&l>> %animation:Welcome%&3 &l%nick%&7&l! &7&l<<'
- '&7Online players: &f%online%'
- '&6Online staff: &e%staffonline%'
- '%animation:ping-tps%'
- ''
- '&7&l Used memory: %memory-used% MB / %memory-max% MB'
- '%animation:MyAnimation1%'
footer:
- '%animation:MyAnimation1%'
- '%animation:time%'
- ''
- '&7Visit our webpage %animation:web%'
yellow-number-in-tablist: ''
group-sorting-priority-list:
- owner
- admin
- mod
- helper
- builder
- premium
- player
- default
Groups:
  Owner:
    tabprefix: '&0&l[&a&lOwner&0&l] &a'
    tagprefix: '&2&lOwner &a'
  Admin:
    tabprefix: '&0&l[&4&lAdmin&0&l] &1'
    tagprefix: '%animation:admin_prefix%'
  Player:
    tabprefix: '&0&l[&7&lPlayer&0&l] &3'
    tagprefix: '&2&lPlayer &3'
  example_group:
    header:
    - This is an example of per-group header/footer
    footer:
    - applied to a group
  _OTHER_:
    tabprefix: '%vault-prefix%'
    tagprefix: '%vault-prefix%'
    tabsuffix: '%afk%'
    tagsuffix: '%afk%'
    customtabname: '%essentialsnick%'
    customtagname: '%essentialsnick%'
Users:
  _NEZNAMY_:
    tabprefix: '&6&lTAB Author &a'
    tagprefix: '&6&lTAB &r&a'
    abovename: '&bOh look, 3 lines of text !'
    belowname: '&eThere''s only one plugin out there supporting it'
  Zinc814:
    customtabname: Zinc814&7(징크)&r
    abovename: '&d[§d§l어드민]&r'
    belowname: '&7징크&r'
  Tashley_Slim:
    abovename: '&d[유저]&r'
    customtabname: Tashley_Slim&7(태슐리)&r
  TABAM_POE:
    customtabname: TABAM_POE&7(포타밤)&r
    belowname: '&7포타밤&r'
    abovename: '&d[플레이어]&r'
  4week:
    customtabname: 4week&7(사주)&r
    belowname: '&7사주&r'
    abovename: '&d[§d§l어드민]&r'
  love5116:
    customtabname: love5116&7(로울)&r
    belowname: '&7로울&r'
    abovename: '&d[§d§l어드민]&r'
  '08_2':
    customtabname: 08_2&7(공팔)&r
    belowname: '&7공팔&r'
    abovename: '&d[§d§l어드민]&r'
  duedos:
    customtabname: duedos&7(도스)&r
    belowname: '&7도스&r'
    abovename: '&d[플레이어]&r'
  Player754:
    abovename: '&d[§d§l어드민]&r'
classic-vanilla-belowname:
  enabled: false
  number: '%health%'
  text: Health
enable-collision: true
revert-collision-rule-in-worlds:
- revertedworld
do-not-move-spectators: false
allow-spectator-bypass-permission: false
unlimited-nametag-prefix-suffix-mode:
  enabled: true
  modify-npc-names: true
  use-marker-tag-for-1-8-x-clients: false
per-world-settings:
  world1:
    header:
    - an example of world with custom
    footer:
    - header/footer and prefix/suffix
    Groups:
      Owner:
        tabprefix: '&0&l[&a&lOwner&0&l] &a'
        tagprefix: '&2&lOwner &a'
  world2-world3:
    header:
    - This is a shared header for
    - world2 and world3
placeholders:
  afk-yes: ' &4*&4&lAFK&4*&r'
  afk-no: ''
  date-format: dd.MM.yyyy
  time-format: '[HH:mm:ss / h:mm a]'
  time-offset: 0
  remove-strings:
  - '[]'
  - < >
rank-aliases:
  Admin: '&4&lADMIN'
  Mod: '&b&lMOD'
  Premium: '&6&lPREMIUM'
  Ultra: '&b&lULTRA'
  Legend: '&a&lLEGEND'
  Titan: '&c&lTITAN'
  Youtuber: '&c&lYOUTUBE'
  _OTHER_: '&7No Rank'
disable-features-in-worlds:
  header-footer:
  - disabledworld
  tablist-names:
  - disabledworld
  nametag:
  - disabledworld
  tablist-objective:
  - disabledworld
  bossbar:
  - disabledworld
  belowname:
  - disabledworld
